### ISSUE TITLE
`--remote-wait` or `--remote-tab-wait` does not wait...

### ISSUE THREAD

**Issue by svanharmelen** [mhinz/neovim-remote#10]
It immediately returns instead of waiting till the file is written or closed.

Additionally it would be great if we can also call wait when using the `-o` or `-O` arguments, so something like `-o --wait` or something like that... Given the wait actually waits that is :wink:

**Comment by svanharmelen** [comment]
@mhinz any thoughts on this one? Any way I can troubleshoot/test this? Did I do anything wrong?

Thx!

**Comment by tpict** [comment]
I have the same issue, for example trying to write a Git commit message with ```---remote-wait``` results in an "empty commit message" error.

**Comment by mhinz** [comment]
Yea, the `*-wait*` family isn't working yet. Actually these are the only flags not working yet.

The problem is that all other features just send a message to the remote instance, but now we have to get the remote instance to send a signal to nvr and nvr receiving it properly.

I look into it.

**Comment by mhinz** [comment]
@bfredl What would be the best approach here?

Basically `nvr` is supposed to wait until a signal from the remote instance is received. And the remote instance is supposed to send that signal when it's exiting.

**Comment by mhinz** [comment]
@svanharmelen @tpict The `-wait` family should work properly now. Please see the latest changes.

**Comment by svanharmelen** [comment]
@mhinz  cool! Will have a look shortly...

**Comment by bfredl** [comment]
@mhinz  That looks like the right approach.

**Comment by mhinz** [comment]
@bfredl Splendid, thanks for the confirmation.

**Comment by mhinz** [comment]
It should work now, but please reopen if it's not the case.

Thanks for urging me to finally implement this. :-)

**Comment by svanharmelen** [comment]
Thanks for fixing this!
