### ISSUE TITLE
Error using `<C-x><C-e>` with `+'setlocal bufhidden=wipe` in terminal mode in ZSH

### ISSUE THREAD

**Issue by 3v0k4** [mhinz/neovim-remote#100]
Not sure if this is related but I have a similar problem as https://github.com/mhinz/neovim-remote/issues/26

I'm on zsh
```
echo $ZSH_VERSION
# 5.7.1
zsh --version
# zsh 5.7.1 (x86_64-apple-darwin16.7.0)
```
which should be the one with the fix.

Neovim
```
nvim --version
# NVIM v0.3.4
```

In my .zshrc
```
export VISUAL="nvr -cc split --remote-wait +'setlocal bufhidden=wipe'"
```

When in terminal mode in nvim I do `<C-x><C-e>` I get
```
  File "/Users/rysiek/Library/Python/3.7/bin/nvr", line 11, in <module>
    sys.exit(main())
  File "/Users/rysiek/Library/Python/3.7/lib/python/site-packages/nvr/nvr.py", line 421, in main
    nvr.execute(options.remote_wait + arguments, 'edit', wait=True)
  File "/Users/rysiek/Library/Python/3.7/lib/python/site-packages/nvr/nvr.py", line 145, in execute
    self.server.command(cmd if cmd else '$')
  File "/Users/rysiek/Library/Python/3.7/lib/python/site-packages/pynvim/api/nvim.py", line 287, in command
    return self.request('nvim_command', string, **kwargs)
  File "/Users/rysiek/Library/Python/3.7/lib/python/site-packages/pynvim/api/nvim.py", line 182, in request
    res = self._session.request(name, *args, **kwargs)
  File "/Users/rysiek/Library/Python/3.7/lib/python/site-packages/pynvim/msgpack_rpc/session.py", line 102, in request
    raise self.error_wrapper(err)
pynvim.api.nvim.NvimError: b'Vim:E20: Mark not set'
```

Without  ` +'setlocal bufhidden=wipe` in my .zscrc
```
export VISUAL="nvr -cc split --remote-wait"
```
the split opens w/o errors.

Let me know if I can provide more info on this in case anybody's willing to help!

**Comment by mhinz** [comment]
Then it's probably something in your environment.

Try this in terminal mode:

```
$ zsh -f
% autoload -z edit-command-line
% zle -N edit-command-line
% bindkey "^X^E" edit-command-line
% export VISUAL="nvr -cc split --remote-wait +'setlocal bufhidden=wipe'"
<c-x><c-e>
```

Does it work with the zsh defaults?

**Comment by 3v0k4** [comment]
That works! But I don't really understand what's going on.

I can do `<c-x><c-e>` in zsh and it works.

If I put `return` at the top of each init file for zsh (see [2.2: All the startup files](http://zsh.sourceforge.net/Guide/zshguide02.html)) and then

```
/usr/local/bin/nvim
:terminal
autoload -z edit-command-line
zle -N edit-command-line
bindkey "^X^E" edit-command-line
export VISUAL="/Users/rysiek/Library/Python/3.7/bin/nvr -cc split --remote-wait +'setlocal bufhidden=wipe'"
```
Then I get the error
```
  File "/Users/rysiek/Library/Python/3.7/bin/nvr", line 11, in <module>
    sys.exit(main())
  File "/Users/rysiek/Library/Python/3.7/lib/python/site-packages/nvr/nvr.py", line 421, in main
    nvr.execute(options.remote_wait + arguments, 'edit', wait=True)
  File "/Users/rysiek/Library/Python/3.7/lib/python/site-packages/nvr/nvr.py", line 145, in execute
    self.server.command(cmd if cmd else '$')
  File "/Users/rysiek/Library/Python/3.7/lib/python/site-packages/pynvim/api/nvim.py", line 287, in command
    return self.request('nvim_command', string, **kwargs)
  File "/Users/rysiek/Library/Python/3.7/lib/python/site-packages/pynvim/api/nvim.py", line 182, in request
    res = self._session.request(name, *args, **kwargs)
  File "/Users/rysiek/Library/Python/3.7/lib/python/site-packages/pynvim/msgpack_rpc/session.py", line 102, in request
    raise self.error_wrapper(err)
pynvim.api.nvim.NvimError: b'Vim:E20: Mark not set'
```

Shouldn't `return`ing from the top of each init file be the same as `zsh -f`?

Also, forgot to mention, I'm using `oh-my-zsh`.

**Comment by mhinz** [comment]
I _think_ that `return` should work, but you could try `exit` instead. If that doesn't work, maybe you didn't catch _all_ config files after all.

I never used oh-my-zsh, but I know it's complex and don't know how it gets installed/sourced, so this might be another potential culprit.

So, I can't help you for finding the actual splitting issue in your config, but if you just want to get it done, just try to avoid the escaping spaces like this:

```
export VISUAL='nvr -cc split --remote-wait +setlocal\ bufhidden=wipe'
```

Hope this helps!

**Comment by 3v0k4** [comment]
Found the problem! I'm leaving the fix here for posterity.

On my machine I have both `/bin/zsh` which is v5.2 and `/usr/local/bin/zsh` which is v5.7.1. oh-my-zsh [set my login shell to `/bin/zsh`](https://github.com/robbyrussell/oh-my-zsh/blob/master/tools/install.sh#L87). Thus, `nvim +terminal` was running v5.2 and not v5.7.1.

To fix the problem either change `shell` in vim `set shell=/usr/local/bin/zsh` (e.g. `init.vim`). In fact, in neovim [`:h :terminal`](https://neovim.io/doc/user/various.html#:terminal) says
> Execute {cmd} with 'shell'

Or, prolly better, make your default login shell the one in `/usr/local/bin/zsh`:
```
sudo sh -c "echo \"/usr/local/bin/zsh\" >> /etc/shells"
chsh -s /usr/local/bin/zsh
```

@mhinz thank you so much for pointing me in the right direction!

**Comment by mhinz** [comment]
Ah! I changed my system's login shell a long time ago, so this simply didn't come to my mind.

> thank you so much for pointing me in the right direction! Is there any way I can offer you a beer? (e.g. donation)

I plan to set up a way for donations for years already, but it never happened. I appreciate the gesture, though!

Anyway, I'm glad it's working for you now and thanks for summing it up so clearly!
