### ISSUE TITLE
closing a commit message with ZZ

### ISSUE THREAD

**Issue by lukekhamilton** [mhinz/neovim-remote#101]
Am using nvr for working with git commit messages within neovim, however when I close a commit message with the ZZ shortcut the terminal is still in a wait mode (used the config in the readme to set this up, with no changes) I then need to end terminal mode and ctrl-C the process for it to then finishs the commit. 

Anyway I can get this to just finish once the the commit message is closed? 
Thanks

**Comment by mhinz** [comment]
The buffer has to be deleted. `ZZ` updates the buffer and closes the window, but doesn't delete the buffer.

See `Use nvr as git editor` under https://github.com/mhinz/neovim-remote#typical-use-cases for a workaround.

**Comment by lukekhamilton** [comment]
Thank you! Fixed my issue. :)

Regards,
Luke Hamilton
Snr Software Engineer
