### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by astier** [mhinz/neovim-remote#108]
This is probably not the right place but my gosh nvr is awesome! I just tinkered a little bit more with it and found the reddit-article which you linked where you can have one nvim-instance per tmux-session. This opens so many new possibilities. I just wanted to say thank for your great work!

**Comment by mhinz** [comment]
Oh, wow.

I think I speak for every OSS maintainer out there when I say that we really appreciate a bit of love for our work every now and then. :heart:

Thank you!
