### ISSUE TITLE
Can't combine `vsplit` with `line number`

### ISSUE THREAD

**Issue by snoblenet** [mhinz/neovim-remote#109]
These work as expected but neither combines the two features I need to use together:

- `nvr -O path/to/file.js`: opens the file in a vsplit at the first line as expected
- `nvr +99 path/to/file.js`: opens the file in an existing window at line 99 as expected

One of these should do what I need, but none of them work:

- `nvr -O +99 path/to/file.js`: opens the file in a vsplit as expected, but does not take you to line 99
- `nvr -O path/to/file.js +99`: opens the file in a vsplit as expected, but does not take you to line 99; also opens a new empty file called `+99`
- `nvr +99 path/to/file.js -O`: throws an `expected at least one argument` error

Thoughts?

**Comment by mhinz** [comment]
Do all these cases work with Vim? If so, it should be changed, of course.

If you just want to get it done, remember that `+` merely executes commands (`:99` in Vim takes you to line 99). So, in the meanwhile, you could use `nvr -c 99 -O path/to/file.js`.
