### ISSUE TITLE
nvr command not found

### ISSUE THREAD

**Issue by CrashyBang** [mhinz/neovim-remote#11]
I keep getting `nvr command not found` even after a successful install, I am using FISH shell could this be effecting that???

**Comment by mhinz** [comment]
Did you figure it out?

If not, how did you install nvr? What OS/distro do you use?

**Comment by CrashyBang** [comment]
Hey @mhinz, yet figured it out was to do with pip setup :)

**Comment by mhinz** [comment]
Ah, splendid. :-)

And sorry for the late response, but I wasn't near computers for some weeks and have to catch up with quite a few things now. Nevertheless I pushed several commits to master just today and will upload a new release to PyPI in the next days.

**Comment by garrettqmartin8** [comment]
@CrashyBang I'm running into the same issue. What did you change in your pip setup?
