### ISSUE TITLE
Problems with fetching neovim version

### ISSUE THREAD

**Issue by copyme** [mhinz/neovim-remote#110]
```
nvr --version
Traceback (most recent call last):
  File "/usr/bin/nvr", line 11, in <module>
    sys.exit(main())
  File "/home/kacper/.local/lib/python3.6/site-packages/nvr/nvr.py", line 372, in main
    version = pkg_resources.require('neovim-remote')[0].version
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 895, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 781, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'neovim>=0.2.3' distribution was not found and is required by neovim-remote
```

but the installed version of neovim is 0.3.5

**Comment by mhinz** [comment]
How did you install neovim-remote? It can't find the Python package called `neovim` (which was lated renamed to `pynvim`), but it should be installed automatically on `pip3 install neovim-remote`.

Does `pip3 install pynvim` solve your issue?

**Comment by copyme** [comment]
Hi @mhinz in my case the python package is provided by the distribution (python3-neovim) and pip3 does not install them once again.

**Comment by mhinz** [comment]
Should work now no matter how the package got installed. ;]

Thanks for letting me know! :sparkles:
