### ISSUE TITLE
 hint: Waiting for your editor to close the file...

### ISSUE THREAD

**Issue by vito-c** [mhinz/neovim-remote#112]
When I am inside a neovim terminal and I run git commit --amend  then save and quit I am greeted with
` hint: Waiting for your editor to close the file...` at my terminal ... I wait and wait and wait and nothing happens then I just <c-c> and it goes away and the commit takes place it's very strange as it just started happening when I enabled some saml github thing.

**Comment by vito-c** [comment]
I think I see the issue I use ZZ to quit the buffer

**Comment by mhinz** [comment]
Yup, the buffer has to be deleted, but `ZZ` or `:wq` etc. just write the buffer and quit the window without deleting the actual buffer.

Running the git editor within `:terminal` is a bit of a hack and not as comfortable as just firing up another shell and running `git commit` there, but _Use nvr as git editor_ at https://github.com/mhinz/neovim-remote#typical-use-cases shows a few ways to improve the experience!
