### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by blankenshipz** [mhinz/neovim-remote#113]
I just installed `neovim-remote` with `pip3 install neovim-remote`; I'm getting this error when trying to run the application:

```bash
Traceback (most recent call last):
  File "/usr/local/bin/nvr", line 6, in <module>
    from nvr.nvr import main
ModuleNotFoundError: No module named 'nvr'
```

System specs:

MacOS Mojave 10.14.5
pip3 19.0.3 from /usr/local/lib/python3.7/site-packages/pip (python 3.7)
Python 2.7.10 

any thoughts what I might have done wrong? It seems like pip might be installing it under a different version of python?

**Comment by blankenshipz** [comment]
I uninstalled and reinstalled and it appears to be working now.

**Comment by TamaMcGlinn** [comment]
I had this exact problem because I had done this:

```
pip3 install nvr
```

which is incorrect; I guess the package used to be called nvr. Solution was as you say; uninstall:

```
pip3 uninstall nvr
```

And use the install method you state:

```
pip3 install neovim-remote
```

Thank you @blankenshipz
