### ISSUE TITLE
Error in wheel file name?

### ISSUE THREAD

**Issue by ar-qun** [mhinz/neovim-remote#12]
neovim-remote-1.1.3.tar.gz
neovim_remote-1.1.3-py3-none-any.whl

As you see tar.gz and whl are named one with underscore and the other with dash. Is is as intended?

**Comment by mhinz** [comment]
Well, the packing does that on its own. It leads to no problems though, as far as I can tell.

It's the same for [python-dateutil](https://pypi.python.org/pypi/python-dateutil/2.5.3) or [msgpack-python](https://pypi.python.org/pypi/msgpack-python).

Additionally, have a look at this discussion: https://github.com/pypa/pip/issues/1150
