### ISSUE TITLE
How do I use IPv6 address for --servername argument?

### ISSUE THREAD

**Issue by unclechu** [mhinz/neovim-remote#125]
`... --servername ::1:9999` -- This doesn't work, I get "can't connect to" error, while using `/etc/hosts` alias works fine (e.g. `... --servername localhost6:9999`).

**Comment by mhinz** [comment]
Is there a nvim with that address or do you want to start a new one?

**Comment by mhinz** [comment]
Should be fixed in 2.3.1.

Thanks! ✨

**Comment by mhinz** [comment]
BTW, `nvr --serverlist` should also show IPv6 addresses since v2.3.2.
