### ISSUE TITLE
cli flag to increase attach retry time

### ISSUE THREAD

**Issue by davidosomething** [mhinz/neovim-remote#128]
something in my nvim is blocking the attach (maybe some plugin)

```
            for i in range(10):
                self.attach()
                if self.server:
                    self.started_new_process = True
                    return True
                time.sleep(0.2)
```

Would like to customize the `10` number by adding `--retry-attach=60`
also may help on a slow computer

**Comment by mhinz** [comment]
Before merging, please see if it's even fixing your problem: https://github.com/mhinz/neovim-remote/pull/130

**Comment by davidosomething** [comment]
i'll use it all day and see if i get any issues :) thanks!

**Comment by davidosomething** [comment]
:( aw still getting issues, my neovim starts and then a few ticks later i get the couldn't attach message
i also get an empty `~/.local/nvimsocket=` file (my `NVIM_LISTEN_ADDRESS` is set to `/Users/me/.local/nvimsocket`)

**Comment by mhinz** [comment]
Maybe nvim was killed so it didn't have the change to remove the socket itself? When there's no nvim running, just `rm ~/.local/nvimsocket` and try again.

**Comment by davidosomething** [comment]
i have NVIM_LISTEN_ADDRESS exported in my zshrc because i don't like to use `/tmp/`
my typical usage is `nvr -s`
and yea, I end up having to `rm` the socket file on each crash, so I've mostly stopped using nvr with no alternative unfortunately

**Comment by mhinz** [comment]
If you don't like stale unix domain sockets because of a Nvim crash, use an IP address instead. E.g. `NVIM_LISTEN_ADDRESS=localhost:12345`.

Nothing that relates to attaching was changed recently, so it would be nice if you could `git bisect` the exact commit. :)

**Comment by davidosomething** [comment]
gonna close, it is probably some issue with my system not allowing python to access socket
