### ISSUE TITLE
`nvr -d` does not `:diffthis` first file for existing nvim processes

### ISSUE THREAD

**Issue by FallenWarrior2k** [mhinz/neovim-remote#137]
When I already have a running nvim process, either through `nvr -s` or by setting `NVIM_LISTEN_ADDRESS` and then starting `nvim` manually, trying to diff files with `nvr -d foo bar` does open two files in a split, but I still need to `:diffthis` the first file after they're opened.
If there's no process yet when I do `nvr -d foo bar`, diff mode is enabled correctly in the new nvim process.
This also happlies with 3 or more files: All files except the first one correctly get added to the diff set.

This happens even without a `~/.config/nvim/init.vim` or `~/.vimrc`, so it doesn't seem to be related to my configuration.

I'm on Arch with these versions:
```
$ nvr --version
nvr 2.4.0
pynvim 0.4.0
psutil 5.6.5
Python 3.7.5 (default, Nov 11 2019, 00:14:32) 
$ nvim --version
NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.3/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

I believe this is caused by the fact that `main2()` only passes `args[1:]` through `Nvr.execute()`, while `args[0]` is opened using `Nvr.fnameescaped_command()`, which does not call `Nvr.diffthis()` internally. See [here](https://github.com/mhinz/neovim-remote/blob/master/nvr/nvr.py#L491) and [here](https://github.com/mhinz/neovim-remote/blob/master/nvr/nvr.py#L499).

This also means that nvr doesn't wait for the first file's buffer to be close before terminating (I tested that), since `Nvr.wait_for_current_buffer()` is never called.

**Comment by sisrfeng** [comment]
Hi, I still meets the bug.
![image](https://user-images.githubusercontent.com/53520949/157373526-4ad8ca93-95d7-46cc-943e-114d94d41dc7.png)

 \nvr -d TrackNet3.py ~/p/TrackNet3.py

![image](https://user-images.githubusercontent.com/53520949/157373589-4291831f-b26a-455c-b3a0-fb0979ba4b0f.png)

fail in another conda env too:
![image](https://user-images.githubusercontent.com/53520949/157373659-3a916f32-6961-410e-ac69-3a9abd830d86.png)

**Comment by FallenWarrior2k** [comment]
My PR #138 fixes this but since it hasn't been merged, you'd have to use my fork if you want this feature right now.

**Comment by sisrfeng** [comment]
I have installed nvr on several machines, and think it annoying to update manual 
I am using:
alias ed='\nvr -d   -c "wincmd h" -c "diffthis"'
