### ISSUE TITLE
`nvr some-file` does not open a file

### ISSUE THREAD

**Issue by xPMo** [mhinz/neovim-remote#150]
neovim is launched with `$NVIM_LISTEN_ADDRESS=/tmp/nvimsocket`, but nvr is unable to attach. Neither can it attach inside a `:terminal`.

[This cast is `nvr -s ~/.profile`](https://asciinema.org/a/9bLh2oCwE5G43MRYHLCpuys8I)

E: I don't show it in the cast, but NVIM_LISTEN_ADDRESS is in the environment of the `:terminal`. **However**, `:echo v:servername` in nvim gives a different path. This path is something like `/tmp/nvimPdLmCJ/0`. This path is also given by `nvr --serverlist`. I suspect that nvim is no longer honoring NVIM_LISTEN_ADDRESS at all.

----

Versions:

- Nvim: v0.4.3
- nvr: 2.4.0
- pynvim: 0.4.0
- psutil: 5.7.0
- Python: 3.8.2

**Comment by xPMo** [comment]
I found it. Nvim had crashed previously and left `/tmp/nvimsocket` behind, therefore would not use it.

**Comment by nyngwang** [comment]
FYI: you can use the lastest syntax: `nvim --listen /tmp/your_name`.
