### ISSUE TITLE
How to clean/clear addresses of long lost nvim processes?

### ISSUE THREAD

**Issue by qazip** [mhinz/neovim-remote#166]
I am trying to create a simple bash-script to have neovim-qt work like sublime-text when opening files. I am using neovim-remote for that. However, I would like a way to clean/clear/delete address of nvim processes that no longer exist..

How can I do that?

**Comment by mhinz** [comment]
Delete addresses from what? neovim-remote isn't storing any addresses.

Do you mean `--serverlist`? If so, it depends on your OS. By default, Nvim uses Unix domain sockets, but TCP works just as well. When an Nvim process gets exited cleanly, it should clean up its sockets as well. (Might take a bit longer for TCP sockets.)

**Comment by mhinz** [comment]
I'll reopen, if there's something I can act on.
