### ISSUE TITLE
is this project alive?

### ISSUE THREAD

**Issue by gigatexal** [mhinz/neovim-remote#169]
Is this project still active? Do you want help maintaining it?

**Comment by ashishbinu** [comment]
Last commit was two years ago. Seems like no one is maintaining it now.

**Comment by Shougo** [comment]
I want to maintain the project.

**Comment by Shougo** [comment]
Fortunately, I know both Python and neovim/Vim implementation.

**Comment by fwsmit** [comment]
I think we need a fork here. The maintainer doesn't seem to be active anymore.

**Comment by Shougo** [comment]
Oh...  OK.  I will fork it.
I have seen him in gitter though.

**Comment by Shougo** [comment]
I accept PRs in forked repository instead.

**Comment by Shougo** [comment]
You should use neovim native remote feature instead.

https://github.com/neovim/neovim/pull/17439

**Comment by fwsmit** [comment]
> You should use neovim native remote feature instead.
> 
> [neovim/neovim#17439](https://github.com/neovim/neovim/pull/17439)

Oh cool!

**Comment by Shougo** [comment]
Some features is not implemented, but the official is important.

**Comment by sisrfeng** [comment]
How to install the alive version?  @Shougo

**Comment by Shougo** [comment]
Nothing alive version unfortunately.
I think to improve built-in remote feature is better.

**Comment by sisrfeng** [comment]
Sad to find there is little update in the forked one:
![image](https://user-images.githubusercontent.com/53520949/162720015-ec4e614a-4005-4eae-9115-4725078477d2.png)

(https://github.com/Shougo/neovim-remote)

**Comment by fwsmit** [comment]
What's wrong with the new built in nvim remote?

**Comment by sisrfeng** [comment]
It lack some features, which can be found in this repo
But this repo seems to cause crash if I load 50+ files in the buffers. (not sure)

**Comment by fwsmit** [comment]
I'd suggest opening an issue at nvim mentioning the missing feature(s) that you need. Don't expect too much development here or at the fork, except if you're submitting it yourself. Most people decided it was best to use the nvim native version.

**Comment by Shougo** [comment]
Yes. The native implementation is better.
I have changed neovim-remote only I needed one.  It is already maintenance mode.

**Comment by Shougo** [comment]
I need the PR feature.

https://github.com/neovim/neovim/pull/17856

Why do you need to use neovim-remote?
I think current neovim remote feature is not same.

**Comment by sisrfeng** [comment]
> I need the PR feature.
> 
> [neovim/neovim#17856](https://github.com/neovim/neovim/pull/17856)
> 
> Why do you need to use neovim-remote? I think current neovim remote feature is not same.

You mean we should use the built-in `--remote`, instead of this repo? 
But I have something like this:
`alias ed='\nvr -d   -c "wincmd h" -c "diffthis"' `
`alias e='nvr -cc tabedit  -c "tabmove -1"'`

But

![image](https://user-images.githubusercontent.com/53520949/166190839-3878928c-71bf-4d25-9edf-9d15be65a6e2.png)

**Comment by Shougo** [comment]
> You mean we should use the built-in --remote, instead of this repo?

Yes.  Because the repository is not maintained anymore.

Oh, if `+cmd` is needed for me.

**Comment by Shougo** [comment]
I have checked current remote feature in neovim.
wait variants and `+cmd` support is only needed.

**Comment by sisrfeng** [comment]
Thx.

> I have checked current remote feature in neovim. wait variants and `+cmd` support is only needed.

You mean that `wait variants` and `+cmd` support are the only missing part in official nvim, and we need to want for them to be implemented?
(Sorry, I'm not a native speaker for English)

**Comment by Shougo** [comment]
> You mean that wait variants and +cmd support are the only missing part in official nvim, and we need to want for them to be implemented?

Yes.

**Comment by mhinz** [comment]
It's still alive. ;-)

**Comment by Shougo** [comment]
Thanks.  If the project still alive, can you include the changes or why `shortmess` is ignored?

https://github.com/mhinz/neovim-remote/pull/154

**Comment by sisrfeng** [comment]
To anyone new to this issue (and my future revisiting):
After this:
![image](https://user-images.githubusercontent.com/53520949/206853528-51f049b2-b732-4271-b10b-941d051d22f6.png)

The fork seems dead now:
![image](https://user-images.githubusercontent.com/53520949/206853540-5c52cfe2-800c-4607-9b83-238f3ead5da0.png)
... 
![image](https://user-images.githubusercontent.com/53520949/206853534-b5ad9035-d1bb-41f7-ac37-e7b90a9fe758.png)

**Comment by Shougo** [comment]
The fork is dead now.  Because the project is alive.
(The development is slowly though)
