### ISSUE TITLE
"--" treated as filename

### ISSUE THREAD

**Issue by gleachkr** [mhinz/neovim-remote#17]
When run in a neovim terminal, the command `nvr -- file.txt` opens two files, one named "--", and the other named "file.txt". 

It would be nice if the initial `--` was ignored. This would make it easier to use nvr as a drop in value for $EDITOR in some contexts (e.g. when running ranger inside of neovim, or when using other scripts that assume that `--` will mark the end of flags and the start of the list of files to be opened).

**Comment by mhinz** [comment]
Fixed, thanks!

**Comment by gleachkr** [comment]
Awesome, thank you!
