### ISSUE TITLE
What will be the fate of neovim-remote now with neovim/neovim#17439 ?

### ISSUE THREAD

**Issue by doronbehar** [mhinz/neovim-remote#175]
So I was wondering are whether there will be backwards incompatible changes for this project now that https://github.com/neovim/neovim/pull/17439 is merged. Or perhaps this project will become obsolete?

Thanks.

**Comment by da99** [comment]
This was discussed in a previous issue: https://github.com/mhinz/neovim-remote/issues/169

If the plugin works, I guess stick with that until Neovim 0.7 comes out. Or forget the plugin and use Neovim nightly which has the 'remote' features: https://github.com/neovim/neovim/releases 
You can download the .AppImage file and test it if you're on Linux... or use MacOs 'brew'.
```
wget https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage
chmod +x ./nvim.appimage
:help remote.txt
```

**Comment by sisrfeng** [comment]
nvim 0.7 has been released!

**Comment by mhinz** [comment]
At the moment the usage of `--remote` in Nvim is still a bit cumbersome, some features miss, and nvr can still be used in `:terminal` to open files without starting a nested nvim process.

I'll try fixing a few low-hanging fruits in the next days, but don't expect me to put too much time into this project. I'll update it for nvim master and then go on.

The goal is that, in the long run, nvim supports everything nvr does natively. (But that still might take a while.)
