### ISSUE TITLE
neovim-remote does not work on the latest neovim

### ISSUE THREAD

**Issue by Shougo** [mhinz/neovim-remote#176]
Because neovim-remote uses `$NVIM_LISTEN_ADDRESS` and `$NVIM_LISTEN_ADDRESS` does not set by neovim.

https://github.com/neovim/neovim/issues/14090#issuecomment-1116142242 

I don't recommend for you to use neovim-remote.  It is not supported anymore.

You should use `nvim --remote` feature instead.

**Comment by mhinz** [comment]
"does not work" is not a valid issue description.

If it's about the use case of using `nvr` within `:terminal`, I'll add support for `$NVIM` today.

**Comment by mhinz** [comment]
`$NVIM` is supported as of 2.4.1.

**Comment by Shougo** [comment]
Thanks.
