### ISSUE TITLE
nvr --remote-wait raises exception

### ISSUE THREAD

**Issue by tecywiz121** [mhinz/neovim-remote#23]
With versions:

- `neovim-remote==1.3.1`
- `neovim==0.1.5`
- `neovim-0.1.5ubuntu1+git201609201032+2778+21~ubuntu14.04.1` installed from `ppa:neovim-ppa/unstable`.

The output from nvr looks like this:
```
$ nvr --remote-wait /etc/fstab
Traceback (most recent call last):
  File "/usr/local/bin/nvr", line 308, in <module>
    main()
  File "/usr/local/bin/nvr", line 263, in main
    neovim.execute(flags.remote_wait, 'edit', wait=True)
  File "/usr/local/bin/nvr", line 61, in execute
    self._execute_remotely(arguments, cmd, wait)
  File "/usr/local/bin/nvr", line 98, in _execute_remotely
    self.server.run_loop(None, notification_cb, None, err_cb)
AttributeError: 'Nvim' object has no attribute 'run_loop'
```

**Comment by mhinz** [comment]
Is there a another nvim instance running at `/tmp/nvimsock` at that point? (`:echo v:servername`)

`pip3 show neovim | grep ^Version` shows 0.1.10?

**Comment by tecywiz121** [comment]
Ah, I see where I screwed up. I updated the python2 neovim, but not the python3 neovim. Thanks!
