### ISSUE TITLE
Does not work with update alternatives

### ISSUE THREAD

**Issue by CrashyBang** [mhinz/neovim-remote#25]
So I have run the following line:

```
sudo update-alternatives --install /usr/bin/vi vi /usr/local/bin/nvr 60
```

Now assuming I can just run `nvr filename` this should work, it does seem to be doing something I end up with kind of nested `nvim` instances.

If I alias this: `alias vi="nvr"` it all works but I am not a fan of aliasing over existing commands and prefer to use update alternatives, any ideas?

Cheers,
Otis.

**Comment by mhinz** [comment]
"kind of nested instances"? What do you see exactly? Screenshot please, if it's hard to explain. :-)

**Comment by CrashyBang** [comment]
Hey @mhinz,

I am an idiot my priority was wrong:

```
sudo update-alternatives --install /usr/bin/vi vi /usr/local/bin/nvr 80
```

So the _kind of nested instances_ was just the default `nvim` in an `nvim terminal` inception!!!

Sorry to bother you.
Cheers!

**Comment by mhinz** [comment]
Hah, glad it's working for you now!
