### ISSUE TITLE
nvr and -stdin-

### ISSUE THREAD

**Issue by funeralismatic** [mhinz/neovim-remote#28]
`nvr` don't recognize the `-` argument as stdin and open buffer named `-` without catch stdin.

Reproduce:

```
 % > echo "1234" | nvim -o -
Nvim: Reading from stdin...
"-stdin-" 1L, 5C"-stdin-" 1L, 5C
```

OK, we have new unnamed split with stdin `1234`.

```
% > echo "1234" | nvr -o -
% >
```

In alredy opened `nvim` we have new empty split named `-`.

**Comment by mhinz** [comment]
Oh, yes. I can add that for `-o` and `-O`.

Do you happen to know how Vim processes `--remote -`? Does it take it literally or read stdin?

**Comment by mhinz** [comment]
Please `pip3 install -U neovim-remote` and see if it works for you.

**Comment by funeralismatic** [comment]
Excellent! Works fine. Thank you.

Please can you add this to `-p` too?

**Comment by mhinz** [comment]
What about now?

**Comment by funeralismatic** [comment]
Works as expected. Many thanks.
