### ISSUE TITLE
can the `-q` flag be added?

### ISSUE THREAD

**Issue by Alok** [mhinz/neovim-remote#29]
I have a script that make `nvr` my `$EDITOR` when I'm using neovim's embedded terminal. I often run a command like `nvim -q <(ag --vimgrep foo bar.txt)` to quickly feed results to the quickfix list. Is there a way to add that flag to `nvr`?

**Comment by mhinz** [comment]
Could you try if the latest version is working as expected?

**Comment by mhinz** [comment]
Oh, of course. Check again!

**Comment by Alok** [comment]
Perfect, thanks. For completeness's sake, you may also want to add the `-t` flag, though I don't use that myself. It would, however, make `nvr` a more or less perfect copy of `nvim` inside `nvim`.

**Comment by mhinz** [comment]
Okay, `-t` got added as well.

**Comment by mhinz** [comment]
> Awesome, thanks. I think `nvr` is basically feature complete at that point
then.

Yay. :-)

Neovim still wants to support these features natively in the future (that's why I never bothered writing tests for nvr), so I'm glad it worked out surprisingly unproblematic so far.

Thanks for your feedback!
