### ISSUE TITLE
Accept line number +<linenum>

### ISSUE THREAD

**Issue by Hotschke** [mhinz/neovim-remote#3]
$ nvr +2 file

opens an empty file `+2` which is not what I want. I want to open `file` at line number 2.
(version of nvr: a308d2d)

Probably the command line parser must be taught to accept also options with a leading `+` additionally to a leading minus sign.

**Comment by mhinz** [comment]
I'll see whether Python's argparse allows to use `+` as flag indicator or not. Will look into it later tonight.

In the meanwhile you can use `nvr file --remote-send 2G` or `nvr --remote-send 2G file` instead.

**Comment by Hotschke** [comment]
Actually, I am coming from here: https://github.com/lervag/vimtex/issues/262#issuecomment-169928222

So the proper configuration would be:

     PDF-TeX Sync support:
     Preset: Custom
     Command: /Users/hotschke/.local/bin/nvr
     Arguments: --servername "/tmp/nvimsocket" --remote-send "%line"G "%file"

Is this correct?

**Comment by mhinz** [comment]
I don't know how the escaping works in that case, but looks about alright. Mabe `--remote-send '<esc>5G'` (or double quotes, it doesn't matter in this case) is a bit more robust, since the `<esc>` ensures you're in normal mode when issuing the `5G`.

**Comment by mhinz** [comment]
So, unfortunately argparse doesn't support `+` options without a lot of pain, so I added `-c` instead.

This should work in your case now:

```
Arguments: --servername "/tmp/nvimsocket" -c %line "%file"
```

**Comment by Hotschke** [comment]
Thanks for your quick update.
Running `$ nvr --servername /tmp/nvimsocket -c 20 notation/mydocument.tex` works as you described.

I have changed the field with the arguments in Skim.app to your suggestion. However, the backwards search within Skim.app still does not work. Too bad that I can't see the actual invoked command and any return values.

**Comment by mhinz** [comment]
How do you invoke it? A quick test in `:term` with `nvr -l -c '?foo'` seems to work.

The only issue I see is that it only jumps to the line of the last occurrence of "foo", but leaves the cursor in the same column as before the jump. But that's an Neovim API issue.

**Comment by Hotschke** [comment]
I invoke the backwards search in Skim.app with `Shift+Cmd+Left Mouse click`.

Yes, `:term` and `nvr -l -c '?foo'` works.

But the problem is that the via the `Shift+Cmd+Left Mouse Click` triggered backwards search in Skim.app does not work.

**Comment by mhinz** [comment]
Oh, I misread that. You can't see which command _skim_ is invoking.
