### ISSUE TITLE
nix package

### ISSUE THREAD

**Issue by nhooyr** [mhinz/neovim-remote#30]
## Issue description

We need a nix package. 

https://github.com/NixOS/nixpkgs

Once a package is merged, since pip doesn't work on nix, we should add a line to the README that says to use `nix-env -iA nixos.python35Packages.neovim-remote` on nixos or `nix-env -iA nixpkgs.python35Packages.neovim-remote` on standalone nix to install neovim-remote,

**Comment by mhinz** [comment]
Please create a PR for adding the installation steps to the README when the package exists and I'll merge it immediately.

Thanks for the heads-up, but I don't consider this an issue, so I'm closing this and wait for your PR. :-)
