### ISSUE TITLE
open in split instead of current window

### ISSUE THREAD

**Issue by nhooyr** [mhinz/neovim-remote#31]
Would be nice to support this. I don't like having my terminal disappear or having to dig through `<C-O>` to get it back.

**Comment by nhooyr** [comment]
Something like `nvr -c "split /tmp"  -c 'doau BufEnter'` takes two times to work, I think because of vim/vim#1353

**Comment by mhinz** [comment]
`nvr -o /tmp`?

**Comment by mhinz** [comment]
Well, I don't think there anything I can do about it. This have to be fixed in *vim.

**Comment by mhinz** [comment]
You can work around it like this:

```
nvr --remote-send '<esc>:split /tmp<cr>'
```

**Comment by nhooyr** [comment]
Thanks!

**Comment by nhooyr** [comment]
For anyone using it in the future, if you don't have `<Esc>` mapped to exit terminal mode, use `nvr --remote-send "<C-\><C-N>:split /tmp<CR>"`

**Comment by Alok** [comment]
Sorry, but couldn't you use `nvr -o`?

**Comment by mhinz** [comment]
@Alok This doesn't work in `:terminal` the first time when using the latest release (nvim v0.1.7).

This is a bug in Vim as well, but fixed in Neovim master already: https://github.com/neovim/neovim/pull/5933
