### ISSUE TITLE
nvr --remote not connecting to socket

### ISSUE THREAD

**Issue by sriramkswamy** [mhinz/neovim-remote#32]
I'm on OS X 10.11.6 and using Neovim version 0.2 and Python version 3.6. I start `nvim` with an `NVIM_LISTEN_ADDRESS` and `nvr` detects this socket but is unable to connect to it. `:echo v:servername` on Neovim returns nothing. Here's a gif of me trying to do this - http://imgur.com/a/opZI8

**Comment by mhinz** [comment]
If Neovim's `v:servername` is empty, there's something wrong in the first place. You can check if nvim is listening on the TCP port via `lsof -n -iTCP | grep nvim`.

E.g. `NVIM_LISTEN_ADDRESS=127.0.0.1:32500` and `NVIM_LISTEN_ADDRESS=127.0.0.1:32500 nvr foo` works as expected for me.

**Comment by sriramkswamy** [comment]
Yes, setting an explicit address works. I'm not sure why the default doesn't seem to work.

As a sidenote, I was wondering if you knew what `autocmd` to trigger after the `TermOpen` event so that Neovim's terminal treats `nvr` as my editor.

**Comment by mhinz** [comment]
> I'm not sure why the default doesn't seem to work.

I only get an empty `v:servernmame` in nvim, when I tried the same socket for 2 different processes. E.g. the first `NVIM_LISTEN_ADDRESS=/tmp/foo nvim` works, but then starting another process `NVIM_LISTEN_ADDRESS=/tmp/foo nvim` will give you an empty `v:servername`.

> As a sidenote, I was wondering if you knew what autocmd to trigger after the TermOpen event so that Neovim's terminal treats nvr as my $EDITOR.

When I understand your question correctly, a simple way would be putting `let $EDITOR = 'nvr'` in your vimrc. So all child processes, including `:terminal` (but also `:!` and `system()`) would use that.

**Comment by sriramkswamy** [comment]
Ah, I see. I might have had a background process maybe.

And the let command doesn’t seem to work. Anyway, since I use Neovim globally, I decided to change the editor in my shell itself. Thanks for your help.
