### ISSUE TITLE
--Remote-wait-silent doesn't seem to work

### ISSUE THREAD

**Issue by Alok** [mhinz/neovim-remote#36]
I run the following commands outside of any nvim instance:

```sh
nvr --remote-silent file.txt
```
and it opens file.txt without showing an error message, as expected.

But `nvr --remote-wait-silent file.txt` shows the error message and then opens file.txt.

**Comment by mhinz** [comment]
Oh, hm. The argument parser expected the wrong arguments.

Should be fixed now, thanks!

**Comment by mhinz** [comment]
I'm pretty sure it's fixed, so I'm closing this.

Thanks for your constant feedback. :-)

**Comment by Alok** [comment]
Oh, I forgot to close this.

Thanks for constantly implementing it =).

**Comment by mhinz** [comment]
I'm grateful enough for people taking the time to report errors, so.. I don't mind closing issues myself, as long as I'm fairly certain the issue is fixed. :-)

**Comment by Alok** [comment]
It's kind of funny actually because I seem to only do it to your repos.
