### ISSUE TITLE
mixing flags with --remote-wait

### ISSUE THREAD

**Issue by Alok** [mhinz/neovim-remote#38]
Running this with latest `nvr` gives `expected at least one argument`.

```
nvr  --remote-tab-wait -q <(ag foo bar)
```

Same if I do something like `nvr --remote-wait -o foo` or `-o --remote-wait`.

**Comment by mhinz** [comment]
**nvr -h**

```
  --remote-tab-wait <file> [<file> ...]
```

Actually all `--remote*` options take at least one file as arguments. :]

**Comment by Alok** [comment]
Except that those two examples don't work.

Running `nvr -o --remote-wait  foo` on the file `foo` gives an error because `-o` expects a file, and switching the order gives the same issue since then `remote-wait` expects a file.

**Comment by mhinz** [comment]
Yes, both options, `-o` and `--remote-wait` expect a file.

I think you want this instead:

```shell
$ nvr -cc split --remote-wait foo
```
