### ISSUE TITLE
Is there some way to open `--remote-wait` in the background?

### ISSUE THREAD

**Issue by Alok** [mhinz/neovim-remote#39]
If I run `nvr --remote-wait foo`, it blocks the terminal until the file
is closed and shows an exit status. Could there be a flag
`--remote-wait-bg` that adds a `&` to the end of the command line, or is
that something best done with an alias?

By the way, splitting the longer named flags into separate flags may be
easier, so you can mix and match them. Something like:

-   `--silent ,-s`,
-   `--remote`,
-   `--wait`,
-   `--tab`,
-   `--bg`.

instead of the rather long list that now exists.

**Comment by mhinz** [comment]
Well, almost all options are modelled after Vim. So keeping the long names is a must and adding even more (even when shorter) options would make the `nvr -h` output even worse. :-P

That said, you can't mix the `--remote*` options anyway (same with Vim). You can use [only of of those](https://github.com/mhinz/neovim-remote/blob/020bb0ca34241bdae3b13bb5551cd6ba11ff019f/bin/nvr#L311-L329).

**Comment by mhinz** [comment]
I just realized that I forgot to answer the main question.. 

What are you trying to do? Why do you want nvr to wait in the background?

In any case, this really sound like this should be solved using an alias.

**Comment by Alok** [comment]
Mutt and git require remote-wait to edit commits and email.

I want to run those in the bg because I very often end up wanting to reuse that terminal that opened `mutt` or `git` for something else. Like many programmers, I'm lazy and don't want to go through the whole  `ctrl-z`, `bg` rigmarole.

**Comment by mhinz** [comment]
You should now be able to use `--remote-wait` and `--remote-wait-silent` for such use cases.

Please see if that works for you.

**Comment by mhinz** [comment]
I consider this solved until told otherwise. ;-)
