### ISSUE TITLE
ssh/scp integration

### ISSUE THREAD

**Issue by nhooyr** [mhinz/neovim-remote#4]
what do you think about neovim/neovim#4109

**Comment by mhinz** [comment]
As far as I see `nvr` would only have to learn taking TCP sockets instead of Unix domain sockets, right?

By the way, I chose Python over all other languages because it's the only officially supported one by Neovim.

(Amusingly I thought about writing a Go provider for a long time already, but didn't came around doing so yet.)

**Comment by nhooyr** [comment]
Indeed. That should be about it. And an option for the ssh host. Though instead of that, the plan might be to use escape sequences to communicate.

**Comment by mhinz** [comment]
The practical approach would be to avoid all the pain by using something like `sshfs` to mount a part of a remote filesystem into the local filesystem and let FUSE handle all the communication transparently.

**Comment by nhooyr** [comment]
@mhinz sometimes you need commands only on the server. some executable to do something and its a nice smooth way to integrate everything.

**Comment by mhinz** [comment]
Dealing with escape sequences is always just a hack in my experience, but let's see how the discussion in that thread works out. :)

**Comment by nhooyr** [comment]
@mhinz well regardless of the discussion neovim-remote should support TCP sockets anyways. It's like 5 lines of code changed.

**Comment by mhinz** [comment]
Closed by https://github.com/mhinz/neovim-remote/pull/6

**Comment by hhsnopek** [comment]
Is it possible to replace tmux sessions with neovim-remote? e.g, leave a neovim session running on server A (with a terminal emulator in a pane), detach from the session and kill the connection to server A and locally and solely with neovim-remote, reconnect to that session

**Comment by tweekmonster** [comment]
@hhsnopek I think you're asking for what I'm currently working: https://github.com/tweekmonster/nmux/

**Comment by mhinz** [comment]
@hhsnopek What @tweekmonster said.

What **nvr** does is sending and optionally receiving the output of any command using either an Unix domain socket (default) or a TCP socket.
