### ISSUE TITLE
[Bug] servers not listed in serverlist

### ISSUE THREAD

**Issue by Fandekasp** [mhinz/neovim-remote#40]
Hi, 

I just installed neovim-remote because I'd like to auto-change my colorscheme in opened vim sessions when pressing an i3-wm keystroke, and the arch neovim wasn't compiled with the +clientserver feature.

If working with a single file, I can get my workflow working fine, but it becomes more difficult when several vim sessions are opened (eg in different tmux panes). 

Pane 1
```
$ nvr --remote file
```
Pane 2:
```
$ nvr --servername /tmp/nvimsocket2 --remote file2
```
Pane 3:
```
$ nvr --serverlist
/tmp/nvimsocket
````

I expected `/tmp/nvimsocket2` to show up in the server list.
I could verify that a command like `nvr --servername /tmp/nvimsocket2 --remote-send ",B<Enter>"` works fine, hence not being able to retrieve the list of servers prevents me from implementing this "update colorscheme to all opened vim sessions" feature.

Could you fix this bug as to show all servers in the serverlist? Or should I raise this issue upstream on the neovim repo ? Or is there a simpler solution for my use-case which I oversaw ?

**Comment by Fandekasp** [comment]
Here is my current hack to bypass serverlist:

.zshrc
```
alias "vim=NVIM_LISTEN_ADDRESS=/tmp/nvimsocket$(ls /tmp/nvimsocket*|wc -l) nvim"
```

script
```
for socket in /tmp/nvimsocket*; do
    nvr --servername $socket --remote-send ",B<Enter>";
done;
```

**Comment by mhinz** [comment]
Yup, it's a known issue but sadly there's no good way to solve it. :<

See: https://github.com/mhinz/neovim-remote/issues/18

**Comment by mhinz** [comment]
As of [this commit](https://github.com/mhinz/neovim-remote/commit/f78e3a9f0e4f9ffa396fc5418da1435a5c808bf3), `--serverlist` should behave as expected now.

**Comment by Fandekasp** [comment]
Thank you ! I wrote a [blog post](https://adrien.is/configuring-solarized-colors/#neovim) about it, if someone is interested.
