### ISSUE TITLE
Attach to nvim instance when used as mergetool "vimdiff"

### ISSUE THREAD

**Issue by hhsnopek** [mhinz/neovim-remote#42]
Is there a way to hook into an existing session of neovim when merging or rebasing?

**Comment by mhinz** [comment]
Just create a custom mergetool for it:

```
[merge]
    tool = nvr

[mergetool "nvr"]
    cmd = "nvr -cc tabnew -o \"$BASE\" \"$REMOTE\" -O \"$LOCAL\" \"$MERGED\""
```

Then, when you have a conflict and you're in `:terminal`, just use `git mergetool`.

The custom command is really ugly and you probably want to customize it further, but it should get you started.

From `git help mergetool`:

```
           When git mergetool is invoked with this tool (either through the -t
           or --tool option or the merge.tool configuration variable) the
           configured command line will be invoked with $BASE set to the name
           of a temporary file containing the common base for the merge, if
           available; $LOCAL set to the name of a temporary file containing
           the contents of the file on the current branch; $REMOTE set to the
           name of a temporary file containing the contents of the file to be
           merged, and $MERGED set to the name of the file to which the merge
           tool should write the result of the merge resolution.
```

**Comment by hhsnopek** [comment]
Awesome! 👍 

This is probably out of scope for neovim-remote now with this question, but I can see this similarly be done for `git rebase`. With either of these commands, am I able to (by default) return to my `:terminal` instance after saving/closing the file?

**Comment by mhinz** [comment]
That is probably worth an own plugin. ;-)

The simplest variant would be to sneak in an automcd like this:

```vim
autocmd BufDelete <buffer> tabclose
```

Since my custom command above creates a new tab, this autocmd would simply close the tab when the current buffer gets closed. Then you'd return to the terminal buffer from the previous tab.

(Note that this doesn't close the buffers opened by git. This needs more work.)

**Comment by hhsnopek** [comment]
another project to add to my list 🙃 

thank you @mhinz!

**Comment by ohcibi** [comment]
The suggested command opens 4 split windows where one is an empty buffer. This should open it in the typical, `left local, center base, right remote, bottom merged` layout:

    nvr -cc tabnew $MERGED -o $LOCAL -O $BASE $REMOTE
            |              |         |
            * open new tab with merged
                           |         |
                           * split `local` horizontally to the top
                                     |
                                     * split base first and then remote vertically to the right

**Comment by mhinz** [comment]
I added the `-d` flag now for opening buffers in diff mode. See https://github.com/mhinz/neovim-remote#typical-use-cases on how to use it.
