### ISSUE TITLE
'--remote*' options require a value, causing '--' to be useless for terminating options before passing filenames

### ISSUE THREAD

**Issue by R3load** [mhinz/neovim-remote#43]
`pacman -Q neovim-remote-git`:
> neovim-remote-git 1.6.1.r0.g53ce66c-1

* How to reproduce:
`nvr --remote -- <file>`

* Expected behaviour:
--remote* options should not require a filename as a value, filenames should be specified as non-option arguments
'--' should terminate the options, treating every argument following it as a non-opt, allowing filenames that begin with '--'
`nvr --remote-tab -- --filename-beginning-with-double-dash --another-one file` should open the following files in tabs:
* `--filename-beginning-with-double-dash`
* `--another-one`
* `file`

* Current behaviour
When using the --remote* options for opening files, they require a value, making the '--'  option terminator useless for passing filenames beginning with double dashes. They'd have to be specified before '--', making them subject to being treated as options.

**Comment by mhinz** [comment]
First of all, `vim --remote -- foo` opens two files as well, `--` and `foo`. Even if that's uncommon behaviour, `nvr` would be consistent.

The real problem here is that Python 3's [argparse](https://docs.python.org/3/howto/argparse.html) considers argument like `--foo` not being part of a previous option anymore. It's considered a "remaining" argument.

I'll look into it.

**Comment by mhinz** [comment]
Should be fixed now. Thanks for bringing this up!

**Comment by R3load** [comment]
It works, thanks! :)

**Comment by R3load** [comment]
The problem (possibly a different, but similar issue) is there again in version `1.8.6.r2.g27c39db-1`

* To reproduce:
`nvr --remote-tab -- --remote-tab`

* Expected behaviour:
open buffer named '--remote-tab' in a new tab

* Current behaviour:
`--` terminates first `--remote-tab` and passes the 2nd `--remote-tab` as a filename to `--remote`, which tries to open the buffer in the current window

**Comment by mhinz** [comment]
Yeah, I think it was an order problem. Please update and see if it works now.
