### ISSUE TITLE
Multiple files in new nvim instance don't open in tabs when using `--remote-tab-*` 

### ISSUE THREAD

**Issue by R3load** [mhinz/neovim-remote#44]
`pacman -Q neovim-remote-git`:
> neovim-remote-git 1.6.1.r0.g53ce66c-1

When spawning a new `nvim` instance (e.g. in case `--servername` is invalid) to open multiple files in tabs (via the `--remote-tab*` options), the buffers open, but not in tabs. Only the first one is shown in the window, the others have to be navigated with `:next` & `:prev`.

**Comment by mhinz** [comment]
Yup, the current fallback is simple: it merely starts a new local process. `nvr --remote foo bar` -> `nvim foo bar`.

In a perfect world we would start a new nvim process, with the given servername, and control that one remotely with all the options that were given to nvr.

Not sure if that's as easy as it sounds. We have to start the process in the background, continue running nvr which accesses the new nvim's API, then foreground the process in the end. Not sure how to do that with Python.

I look into it.

**Comment by R3load** [comment]
How about forking a delayed `nvr --remote-tab` to wait for the new `nvim` instance (wait until the `nvim`'s `'v:servername` is readable maybe? the file, not the var, of course), then execute the commandline once it's ready? I know `nvim` flips after `fg`, so getting the pid is tricky in bash, I don't know about python though.

**Comment by mhinz** [comment]
Please check out the `new-nvim-instance` branch and see if it works as expected.

**Comment by mhinz** [comment]
It passes all my local tests, so I'm closing this. Please reopen this if there are any issues for you.

And thank you for bringing this up! 🎉
