### ISSUE TITLE
Trying to open a file without read permissions results in exit code 0 and no error message

### ISSUE THREAD

**Issue by R3load** [mhinz/neovim-remote#45]
On `nvr --remote <file>`, if `<file>` is not readable, `nvr` exits with code 0 (success) anyway.

It seems `nvim` will only show the `Permission denied:` error message after `:bufdo bun!` (or unloading all the buffers).

Took me a while to figure out why files were failing to open silently, the only indication is a potential status line or tabline change (or a blink, not sure).

**Comment by mhinz** [comment]
All kinds of things could happen on the remote site. The remote process could also be owned by another user with different permissions, so there's no sane way to check for something like this from nvr's side.

Even if there is a way, it would be no simple one and it would only be one. Then we'd also have to do the same for similar issues adding lots of code to the script that's not related to its main task. So, even if someone would provide a PR for it, I'd most probably not merge it (unless the author found a short and simple solution).

Maybe Neovim's API learns about basic error handling in the future.

Neovim plans to add the `--remote` flags back in the future, deprecating this repo, so I won't dive into such issues, sorry. :-)

**Comment by R3load** [comment]
Makes sense. I guess it's Neovim's fault after all, and it's not a big issue anyway since once you know how the error manifests itself, it should be easy to figure out the problem. Thanks :)
