### ISSUE TITLE
-c does not work with --remote-wait

### ISSUE THREAD

**Issue by mbudde** [mhinz/neovim-remote#46]
```
$ nvr --remote      foo -c 'normal ihello'  # This works
$ nvr --remote-wait foo -c 'normal ihello'  # This doesn't
```
Looking at the code it seems that `-c` options are not used if using a `--remote*wait*` option. Is this intentional? `nvim foo -c 'normal ihello'` works so I would expect `nvr --remote-wait` to work the same way.

**Comment by mhinz** [comment]
Please update and see if the latest version works for you.

**Comment by mbudde** [comment]
Yeah, it looks like that does it 👍 Thank you for the quick response.

**Comment by mhinz** [comment]
🤘  Thanks for bringing it up!
