### ISSUE TITLE
Different command for nvr

### ISSUE THREAD

**Issue by ysolis** [mhinz/neovim-remote#48]
I had configured neovim in my machine (Ubuntu 16.04 LTS) with neovim-gnome-terminal wrapper, to have a 'gui' for me.

now, I see that neovim-remote call directly 'nvim' (line 78 in `nvim/nvim.py` file).

can be possible to setup this command with an ENV var for example ? In my case I have 'neovim' command in my path (that call neovim-gnome-terminal wrapper' and I change in this line to 'neovim' command and works.

this can be an ENV variable that if is setup can be used and if is not, we use `nvim` command

the same thing can be for silent mode, that can be default if an ENV var is setup too.

**Comment by mhinz** [comment]
I totally see the need for customizing the command used by nvr. Using an environment variable for it also makes sense in this case.

Adding env var support just for silent mode seems a bit overkill to me though. :-)

So, how does support for `$NVR_CMD` sound?

**Comment by ysolis** [comment]
sounds good to me :)

P.D. silent mode, can we see this in another issue ?

**Comment by mhinz** [comment]
`$NVR_CMD` should work now!

> P.D. silent mode, can we see this in another issue ?

Why do you need that as env variable if `-s` already exists?

**Comment by ysolis** [comment]
check this, when no neovim is running, this message appears in silent mode (and launch neovim and create `/tmp/mvimsocket` )

![image](https://user-images.githubusercontent.com/9123933/28640624-ed466fa4-7211-11e7-8bee-65af665a5237.png)

**Comment by mhinz** [comment]
Oh, ah. Yes.. `nvr foo` is `nvr --remote foo` and the `--remote` flags don't take `-s` into account yet. All other options do. I'll fix that.

But `$NVR_CMD` is working as expected?

**Comment by mhinz** [comment]
The above commit should make `-s` work as expected, even for the `--remote` options.

**Comment by ysolis** [comment]
-s works, but now neovim-remote launch a new nvim console every time, saying that can't connect to /tmp/nvimsocket ... $NVR_CMD set to nvim and neovim-gnome-wrapper, same scenario :(

**Comment by mhinz** [comment]
Does `/tmp/nvimsocket` exist and there is a nvim instance running where `:echo v:servername` is `/tmp/nvimsocket`?

**Comment by ysolis** [comment]
my mistake, I quit neovim and after this /tmp/nvimscket remains, so I delete the socket, restart with nvr -s and it works!

**Comment by mhinz** [comment]
Oh, usually nvim should remove the socket on its own, except when it got killed.

Anyway, I guess this can be closed now?

**Comment by ysolis** [comment]
yes :) close this one ... thanks!

**Comment by mhinz** [comment]
> add the $NVR_CMD info in the README.rst file

Done.

Thanks for bringing up all these issues!
