### ISSUE TITLE
jump-to-line behaviour is broken

### ISSUE THREAD

**Issue by nacnudus** [mhinz/neovim-remote#5]
Commit a308d2d0c0874a500f58c4ef016e63593667c19c has broken inverse search in synctex, since `--remote +117 /path/to/file.tex` is now interpreted as two separate filenames.

**Comment by mhinz** [comment]
`--remote` takes a list of files and `+` is not understood by the tool. use `--remote /path/file.tex -c 117` instead. The order doesn't matter, so `-c 117 --remote /path/file.tex` works just as well.

**Comment by nacnudus** [comment]
That works, thank you.

**Comment by lervag** [comment]
Note, though, that this syntax is not compatible with normal Vim syntax.

I'm curious, if this used to work as claimed in the [vimtex thread](https://github.com/lervag/vimtex/issues/262#issuecomment-175882228), why has it been broken in recent updates? It is claimed that the commit d206e65548e6a8f95300f8fb7ecaa0a162f90cd5 should still work with the `+` syntax.

**Comment by mhinz** [comment]
In the beginning `nvr` used to be a wrapper that fell back to normal `nvim` for unknown arguments. So when `+` was given, it always started a new instance of nvim instead of relaying the line number to the already opened instance. It was more confusing than helpful.

The change was: [commit](https://github.com/mhinz/neovim-remote/commit/5b1cd8ee03239de4ddf6a22457755c0be141223d)

The new approach is much more predictable.

``` 
$ nvr -h
usage: /Users/mhi/bin/nvr [arguments]

Helper tool for nvim that provides --remote and friends.

All unused arguments will be implicitely fed to --remote-silent.
Thus the following two lines are equivalent:

    $ nvr --remote-silent foo bar quux
    $ nvr foo bar quux

optional arguments:
  -h, --help            show this help message and exit
  -l                    change to previous window via ":wincmd p"
  -c <cmd>              execute single command
  -o <files>            open files via ":split"
  -O <files>            open files via ":vsplit"
  --remote <files>      open files via ":edit"
  --remote-wait <files>
                        as --remote
  --remote-silent <files>
                        as --remote, but don't throw error if no server is
                        found
  --remote-wait-silent <files>
                        as --remote, but don't throw error if no server is
                        found
  --remote-tab <files>, -p <files>
                        open files via ":tabedit"
  --remote-send <keys>  send key presses
  --remote-expr <exprs> [<exprs> ...]
                        evaluate expressions in server and print result
  --servername <sock>   path to unix socket (overrides $NVIM_LISTEN_ADDRESS)
  --serverlist          prints socket path to be used

Happy hacking!
```

**Comment by lervag** [comment]
I see. Still, the current version is not compatible with regular Vim. I'm curious if it is not possible to manually parse the provided argument to `--remote`. See Vim help docs `:h --remote`, which gives the syntax for the `--remote` option:

```
--remote [+{cmd}] {file} ...
```

> There is one optional init command: +{cmd}. This must be an Ex command that can be followed by "|".

Perhaps I am wrong and this is difficult to parse?

**Comment by mhinz** [comment]
Oh, they should add that to the manpage. *cough*

When given `--remote +cmd file1 file2`, "cmd" is executed for the last file, I guess?

**Comment by lervag** [comment]
I just tested: The `cmd` is executed for the first file, not the last. It seems it works like this: `--remote` opens the list of files, the first file becomes the first buffer. After the files have opened, the `cmd` is executed.

And yes, I agree, this should have been added to the manpage, or at least there should be a reference in the man page for the `--remote` option and friends to the relevant section in the help docs.

**Comment by lervag** [comment]
Btw: If it is possible to implement this `+cmd` feature, then `neovim-remote` will work very well as a compatibility layer between Vim and neovim. I still hope that the `--remote` options are added to neovim directly, but in the meantime, this would allow me to avoid (IMHO unecessary) code complexity to support neovim in vimtex.

**Comment by mhinz** [comment]
The above commit should make it work.

**Comment by lervag** [comment]
Great, thanks! @nacnudus Could you please test if this solves the vimtex issue?

**Comment by nacnudus** [comment]
It works for me.  Thanks both!

**Comment by mhinz** [comment]
Yay. :-) Thank you both for reporting this issue.

**Comment by lervag** [comment]
Great, I'm happy to hear it!

**Comment by lervag** [comment]
No problem, I'm just happy that my input to the issue was useful! Thanks for the great work and effort in developing neovim-remote! I hope that it might someday be redundant, but until that day it is very useful!
