### ISSUE TITLE
Documentation for `-p` flag is hard to find

### ISSUE THREAD

**Issue by nelstrom** [mhinz/neovim-remote#50]
Here's an excerpt from the output of `nvr --help`:

    --remote-tab [<file> [<file> ...]], -p [<file> [<file> ...]]
                          Like --remote, but use :tabedit.

    ...other flags...

    -o <file> [<file> ...]
                          Open files via ":split".
    -O <file> [<file> ...]
                          Open files via ":vsplit".

I was curious to know if there was a `:tabedit` equivalent to the `-o` and `-O` flags. I eventually realised that the `-p` flag was what I was looking for, but it took me a while to find it!

I suggest that the `nvr --help` output should read as follows:

    --remote-tab [<file> [<file> ...]]
                          Like --remote, but use :tabedit.

    ...other flags...

    -o <file> [<file> ...]
                          Open files via ":split".
    -O <file> [<file> ...]
                          Open files via ":vsplit".
    -p <file> [<file> ...]
                          Open files via ":tabedit".

Making the `-p` flag much easier to find. Are there any technical reasons why the documentation doesn't read this way already?

**Comment by mhinz** [comment]
I guess my reasoning was that `-p` and `--remote-tab` take the exact same code path, so it would make sense to document them in the same place.

But I agree, a clearer documentation is more important. :+1:

**Comment by nelstrom** [comment]
I can see how you would reach that conclusion!

**Comment by nelstrom** [comment]
It's funny how things can look so different when you compare the viewpoint of the author with that of a user.
