### ISSUE TITLE
neovim-remote fails on modified buffer

### ISSUE THREAD

**Issue by clason** [mhinz/neovim-remote#54]
As the title says: I get an error message calling `nvr` whenever I have unsaved changes in the current buffer.

### Steps to reproduce:

1. `nvim -u NONE test`
2. insert a single character, do not save
3. `nvr --remote-silent --servername $V:SERVERNAME +1 test`

(This is on `NVIM v0.2.1-653-g5bec94652` and neovim-remote 1.8.0, both macOS and Linux.)

### Observed outcome:

```
Traceback (most recent call last):
  File "/usr/local/bin/nvr", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/nvr/nvr.py", line 350, in main
    neovim.execute(options.remote_silent + arguments, 'edit', silent=True)
  File "/usr/local/lib/python3.6/site-packages/nvr/nvr.py", line 109, in execute
    self.server.command('{} {}'.format(cmd, prepare_filename(fname)))
  File "/usr/local/lib/python3.6/site-packages/neovim/api/nvim.py", line 218, in command
    return self.request('nvim_command', string, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/neovim/api/nvim.py", line 131, in request
    res = self._session.request(name, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/neovim/msgpack_rpc/session.py", line 98, in request
    raise self.error_wrapper(err)
neovim.api.nvim.NvimError: b'Vim(edit):E37: No write since last change (add ! to override)'
```

### Expected outcome:

Jump to line 1, even if it is changed (which is how `vim` behaves.)

This is quite useful when editing LaTeX files, where saving the buffer triggers -- possibly lengthy -- compilation in the background; see https://github.com/lervag/vimtex/issues/924.

**Comment by mhinz** [comment]
Thanks for reporting this issue!

The best way to solve this problem was temporarily resetting `&modified`.

You can try the latest master or updating via pip3 to 1.8.1.

**Comment by clason** [comment]
That was quick! But this reverts the buffer to the state when the server was started (and not just to the last write), which is not quite the desired behaviour?

**Comment by mhinz** [comment]
*cough*

Please try 1.8.2.

**Comment by clason** [comment]
Works like a charm now, thank you very much!

**Comment by mhinz** [comment]
Thanks for reporting this! *\*high-fives vimtex\**
