### ISSUE TITLE
nvim nesting, trying to debug

### ISSUE THREAD

**Issue by techFishIO** [mhinz/neovim-remote#58]
Hi, hoping someone can chime in and help me debug my nvim nesting issue. When I go through the example pattern of opening a git commit, I end up with nested nvim processes even when setting the `$VISUAL` variable.

If you have any info that might help me figure out what I'm doing wrong... :)

$EDITOR
```
echo $EDITOR
nvim
```

.vimrc
```
if has('nvim')
  let $VISUAL = 'nvr -cc split --remote-wait'
endif
```

echo $VISUAL in an nvim :terminal
```
echo $VISUAL
nvr -cc split --remote-wait
```

git editor
```
[core]
    editor = /usr/local/bin/nvim
```

Nested nvim after `git commit` :(
![nvim-nesting](https://user-images.githubusercontent.com/1899850/30237284-8a88f7b6-94e3-11e7-9ac9-33cf004a951c.png)

**Comment by mhinz** [comment]
The `editor = nvim` setting takes precedence over `$VISUAL`. So, just removing that line should make it work in `:terminal`.

But since you usually also want it to work from the shell (outside of `:terminal` that is), I'd suggest using the other method mentioned:

gitconfig
```
[core]
    editor = nvr --remote-wait-silent
```

HTH

**Comment by techFishIO** [comment]
@mhinz Thanks a ton for the response. I ended up realizing this (obvious) fact and forgot to close the issue.
