### ISSUE TITLE
Installation without pip?

### ISSUE THREAD

**Issue by KillTheMule** [mhinz/neovim-remote#59]
I'd love to use nvr at work, could you provide the steps to install it without using pip? I'd really be grateful, thanks!

(e) Alternatively, could you describe installation with pip, bit without an internet connection? I can manually download things from the browser, but I have not been successfull in getting pip to work with our proxy.

**Comment by mhinz** [comment]
Sorry for the long delay, but I was quite busy lately!

I moved all the installation instructions into an own file. See https://github.com/mhinz/neovim-remote/blob/master/INSTALLATION.md#from-zip

**Comment by KillTheMule** [comment]
Awesome, thanks a lot!
