### ISSUE TITLE
Create new nvim instance when no argument is given

### ISSUE THREAD

**Issue by mhinz** [mhinz/neovim-remote#62]
**Before**

`nvr` and `nvr -h` output the help.

**After**

`nvr` opens a new nvim instance and `nvr -h` outputs the help.

**Comment by davidosomething** [comment]
yessss i've been wanting this; been defaulting to `--remote-silent +enew`

**Comment by mhinz** [comment]
I pushed v1.8.5 which defaults to `--remote-silent` when no argument was given!
