### ISSUE TITLE
-bash: nvr: command not found

### ISSUE THREAD

**Issue by simon-bigsofa** [mhinz/neovim-remote#64]
Followed instructions for installation but `nvr` command not found.

`pip3 install --user --upgrade neovim-remote`
`nvr -h`
`-bash: nvr: command not found`

Python 3 installed on MacOS Sierra via Homebrew.

**Comment by mhinz** [comment]
The instructions also say to add `~/.local/bin` to `$PATH` if you install with `--user`. :)

**Comment by mhinz** [comment]
Hmm, I just learned that Python on macOS only used `~/.local/bin` up to 3.2. Then they switched to `~/Library/Python/<version>/bin`. That directory is controversial and might change in the future _again_.

But currently, if you use Python3 from homebrew, `pip3 install neovim-remote` should install to `/usr/local/bin/nvr` and `pip3 install --user neovim-remote` to `~/Library/Python/3.6/bin/nvr`.

I'll change the docs accordingly.

**Comment by mhinz** [comment]
Okay, I updated the docs.

If you don't have a good reason for using `--user`, I'd suggest just using `pip3 install` which installs to `/usr/local/bin` which is in $PATH by default.

**Comment by simon-bigsofa** [comment]
Yep, adding `Library/Python/<version>/bin` to `$PATH` did the trick.

Thanks, Marco!

**Comment by mhinz** [comment]
You're welcome and thanks for bringing this up!

**Comment by Nishant-Pall** [comment]
Ummm, this might sound like a newbie query but how do I add ~/.local/bin to PATH, I tried export=~/.local/bin but that didn't work in fish shell.
