### ISSUE TITLE
`-p` does nothing and exits with code 0

### ISSUE THREAD

**Issue by R3load** [mhinz/neovim-remote#65]
Version: `1.8.6.r2.g27c39db-1`

* To reproduce:
`nvr -p foo bar`

* Expected behaviour:
open files `foo` and `bar` in tabs, one per file

* Current behaviour:
no output or errors
exits with code 0

The same happens when nvim isn't running yet.

**Comment by mhinz** [comment]
Should be fixed now. Mind that there's a slight difference between `vim -p foo bar` and `nvr -p foo bar` when Neovim isn't started yet, because the latter will first fire up Neovim and then add 2 _additional_ tabs instead of reusing the first one.
