### ISSUE TITLE
Option NOT to start a neovim process?

### ISSUE THREAD

**Issue by jorgesca** [mhinz/neovim-remote#68]
I don't know if this makes sense, here's the issue I have setup and IDE to start neovim for editing files. I use the terminal version of neovim. If the server has not been started when I ask the IDE to open a file, nvr will start a neovim instance, which actually blocks the IDE itself. Is there a way to avoid this?
If I start a neovim server first, all works fine:

$ NVIM_LISTEN_ADDRESS=/tmp/nvim_quartus nvim

The IDE is configured to do this for opening files:
/usr/bin/nvim --servername /tmp/nvim_quartus --remote +%l %f (where %l gets replaced by the line number and %f by the file name)

**Comment by mhinz** [comment]
Oh, I see. This was meant for people who alias `nvr` to `nvim`.

I'll add a `--nostart` option!

**Comment by jorgesca** [comment]
Excellent, thanks!

**Comment by mhinz** [comment]
I'll upload a new version together with some other fixes later today.

Thanks for reporting!
