### ISSUE TITLE
neovim-remote issues neovim v0.2.2.

### ISSUE THREAD

**Issue by rvega** [mhinz/neovim-remote#69]
I just updated to neovim v0.2.2 and I'm having some issues with neovim-remote. I'm using neovim-remote 1.8.10. Here's what I'm doing:

On one terminal I do `NVIM_LISTEN_ADDRESS=/tmp/foo /usr/bin/nvim`. Nvim starts fine and /tmp/foo is created. On another terminal I do `nvr --servername /tmp/foo --remote-silent some-file` and nothing happens. 

If I change --remote-silent for --remote, it works ok.

Also, when the instance of nvim is editing an unsaved file and I try to open  another file from the second terminal as explained above, nothing happens. I used to get a nice error message explaining there was an unsaved buffer.

**Comment by mhinz** [comment]
I have to admit that quite a bit workarounds were added lately. This issue you mention is a result of that.

I'm relentlessly refactoring at the moment and your issue will be fixed in the process.

**Comment by mhinz** [comment]
The new version should be on PyPI later today. Thanks for the report!
