### ISSUE TITLE
Consider supporting Windows

### ISSUE THREAD

**Issue by burgealex** [mhinz/neovim-remote#70]
Windows lovers use neovim too =).

**Comment by burgealex** [comment]
Closed duplicate.  Found out that it is not possible ( per another issue ).  So sad.  Guess I'll have to wait for support in neovim.

**Comment by mhinz** [comment]
I have so little Windows knowledge that even having a Win VM around doesn't help me much.

I'd welcome any patches, though! I mean, the code that forks nvim from nvr is probably totally different on Windows, but supporting --remote and friends shouldn't be too hard and would still be a big win.
