### ISSUE TITLE
Is it possible to pass a parameter to a vim command via stdin?

### ISSUE THREAD

**Issue by andreasthoelke** [mhinz/neovim-remote#72]
I’m wondering if there is a way to pass a parameter/string to a vim command (using `-c`) or remote-expression (using `—remote-expr`)?
I tried 

- `echo "echo 'hi'" | nvr -c -` and 
- `echo "SomeTest1(‘hi’)” | nvr --remote-expr`, 

but this doesn’t seem to work.
Ideally `nvr` would even help me to concatenate command and parameter, e.g. something like 
`pwd | nvr -c "cd" -` would work.

**Comment by mhinz** [comment]
Okay, `-c`, `-cc`, and `--remote-expr` all read from stdin now. Thanks for bringing that up!

But the concat example won't work that way. `-c` only takes one argument, but you specify two. That will simply execute `:cd` and then act the same as `pwd | nvr -` which will put the stdin in a new buffer analog to `pwd | vim -`.

You can use something like this instead:

```
$ nvr -c "cd $(pwd)"
```

**Comment by andreasthoelke** [comment]
Tried it, works! Amazing, thank you so much!!
