### ISSUE TITLE
How to diagnose Neovim-Remote behaviour

### ISSUE THREAD

**Issue by snoblenet** [mhinz/neovim-remote#75]
NVR generally works for me, but sometimes I get weird behaviour, like:
- a full-screen of Python-looking errors that disappear before I can read them
- two windows opening in Neovim, one with the expected file and one empty
Does NVR save a log somewhere that I can read to work out what's going on?

**Comment by mhinz** [comment]
- Well, without the error message there's not much that I can do. :-)
- What command is used when it opens 2 windows? There's no logging. Usually commands are given without change to the [python-client](https://github.com/neovim/python-client) which takes further steps.

**Comment by snoblenet** [comment]
Sorry. The page full of error codes flashes for a second then disappears.
