### ISSUE TITLE
-o has a user-unfriendly command injection via pipe characters

### ISSUE THREAD

**Issue by lf-** [mhinz/neovim-remote#77]
I'm trying to use nvr to open a terminal in a new split with arguments from the command line somehow, but so far I have been unable to work out how to set that up so it is passed "securely" and cannot have anything injected into it accidentally. I then looked into how the `-o` option worked since it must do something similar, but I found that it effectively just concatenates the filename into a vim command.

This breaks accesses to files which have pipes in their names.

I *think* this may be able to be fixed by calling functions from vimscript, but I haven't come across any that look useful for changing the open file in a buffer.

~~~A feature that would very much help in that vein would be a way of using `nvim_set_var()` from a command line argument, which would completely fix my terminal issue.~~~ done #76

### Repro

`nvr -o 'f|term'`

### It should

Open the file with the name `f|term`.

### It does

Opens a new split with a terminal in it and leaves the buffer for the file f open in the background (at least  with `:set hidden`).

**Comment by mhinz** [comment]
nvr now filters everything through `fnameescape()` instead of doing the escaping in Python.

Thanks for bringing this up! ✨

**Comment by mhinz** [comment]
I added a test for this and also changed how the tests work. They should be much easier to read and write now.

**Comment by lf-** [comment]
Not quite fixed:

`python nvr/nvr.py -o "1234' + system('echo y > f')) + echo('"`

Sorry, I've been playing too many CTFs and looking for injections.

That snippet should not create the file `f` if escaping works. But due to the new escaping bug, it is now broken. It will throw an exception but not before it executes that nefarious command. On a more practical note, the new escaping logic also breaks real file names with single quotes in them in addition to made-up injection attack file names.

The solution to this that I found was to put the string in a variable and then execute the desired function giving the variable as an argument, moving the onus of escaping (if there even is any) into neovim-python, msgpack, and neovim itself. This is what #76 was for.

**Comment by mhinz** [comment]
@lf- 

I found out that the Python API exposes equivalents for all VimL functions. These should avoid all quoting issues. Please try again with the latest version.
