### ISSUE TITLE
nvr can't find server

### ISSUE THREAD

**Issue by mrbig033** [mhinz/neovim-remote#78]
I'm running `MX Linux 17` and `NVIM v0.2.3-820-g9cefd83c`.

When I run `nvr --remote file1 file2` it opens the two files, no problem. But when I try `nvr --remote-send 'iabc<esc>'` it gives the error message below and opens a new nvim instance. I have exported and sourced `NVIM_LISTEN_ADDRESS=/tmp/nvimsocket nvim` to my environment variables. 

The error message:

```
[!] Can't connect to: /tmp/nvimsocket

    The server (nvim) and client (nvr) have to use the same address.

    Server:

        Expose $NVIM_LISTEN_ADDRESS to the environment before
        starting nvim:

        $ NVIM_LISTEN_ADDRESS=/tmp/nvimsocket nvim

        Use `:echo v:servername` to verify the address.

    Client:

        Expose $NVIM_LISTEN_ADDRESS to the environment before
        using nvr or use its --servername option. If neither
        is given, nvr assumes "/tmp/nvimsocket".

        $ NVIM_LISTEN_ADDRESS=/tmp/nvimsocket nvr file1 file2
        $ nvr --servername /tmp/nvimsocket file1 file2
        $ nvr --servername 127.0.0.1:6789 file1 file2

    nvr is now starting a server on its own by running $NVR_CMD or 'nvim'.

    Use -s to suppress this message.
```

**Comment by mhinz** [comment]
I guess the `--remove-send` was a typo. :)

I can't really see why `nvr --remote` would work and `nvr --remote-send` wouldn't. Make sure that `/tmp/nvimsocket` doesn't exist already and that `:echo v:servername` outputs `/tmp/nvimsocket` in nvim.

**Comment by mrbig033** [comment]
I figured it out... I had create a /tmp/nvimsocket nvim before trying to make it work. Nevermind about that!

But since I got your attention (:D), let me ask one thing: is it possible to use neovim-remote like people use tmux or emacslient? I mean, opening several clients atached to the same server? How can I do that?

**Comment by mhinz** [comment]
Hmm, to do what exactly?

I mean, each nvim process is a server on its own. nvr merely executes things on behalf of one of these servers. If I'm not mistaken, emacsclient works the same.

**Comment by mrbig033** [comment]
The reason for that would be to cut a few fractions of of a second during startup :P
I never used, but AFAIK, emacsclient works the way I described, I mean, you can close and reopen Emacs several times a day without having to wait for it to load.

**Comment by mhinz** [comment]
I think that's less of a problem in the Vim world, since Vim usually starts quite a bit faster than Emacs with many modes installed. :-P

But no, that's currently not possible with Neovim. I understand that a _real_ server would be pretty cool. There's an issue for it though: https://github.com/neovim/neovim/issues/5035

So, maybe in the future.. :-)

**Comment by mrbig033** [comment]
Cool, thanks!
