### ISSUE TITLE
Publish on pypi

### ISSUE THREAD

**Issue by rgrinberg** [mhinz/neovim-remote#8]
Would be great to easily install and upgrade this useful utility.

**Comment by mhinz** [comment]
I knew this day would come.. :-) I refrained from doing so, since I usually don't program in Python but I see all the advantages of it.

I'll add it to my "today" todo list.

**Comment by mhinz** [comment]
It's registered and uploaded now, but it might take some hours until you can find it via `pip3 search neovim`.

:arrow_right: https://pypi.python.org/pypi/neovim-remote

**Comment by mhinz** [comment]
Update: I just learned that you can use `pip3 install neovim-remote` already, but you can't search for it, due to a bug.... https://bitbucket.org/pypa/pypi/issues/326/some-packages-not-showing-up-when

**Comment by lbischof** [comment]
Thanks very much! Great plugin!

**Comment by mhinz** [comment]
@lbischof I'm glad you like it!

I guess this issue can be closed now.
