### ISSUE TITLE
nvr mistyped arg opens buffer

### ISSUE THREAD

**Issue by lxndrcx** [mhinz/neovim-remote#80]
Currently if I type `nvr --server-list` i get a new buffer editing the file `"--server-list"`. Is that desired? I would think it should throw an error  like "no such option" or something.

**Comment by mhinz** [comment]
Hi,

It actually works the same in Vim. :)

Mind that `nvr foo` is a shortcut for `nvr --remote-silent foo`.

If you use `vim --servername foo` in one shell, and `vim --servername foo --remote-silent --server-list` in another, a file `--server-list` gets opened as well.

Thanks for opening an issue anyway!
