### ISSUE TITLE
Ex command parsing fails when calling the pass command

### ISSUE THREAD

**Issue by munyari** [mhinz/neovim-remote#81]
Trying to use pass to edit passwords inside terminal mode in nvim.

When I run `EDITOR="nvr +'set spell'" pass edit tmp`

Expected behavior:
nvr should open a new buffer containing the temporary file created by pass, with `:set spell` called on startup.

Actual behavior:
Two buffers are opened. One is titled `spell'` (note the trailing apostrophe, maybe a parsing issue?) and the other is the temporary file created by pass. In the terminal buffer, I see this stacktrace

```
Traceback (most recent call last):
  File "/usr/bin/nvr", line 11, in <module>
    load_entry_point('neovim-remote==2.0.4', 'console_scripts', 'nvr')()
  File "/usr/lib/python3.6/site-packages/nvr/nvr.py", line 412, in main
    nvr.execute(arguments, 'edit', silent=True)
  File "/usr/lib/python3.6/site-packages/nvr/nvr.py", line 132, in execute
    self.server.command(cmd if cmd else '$')
  File "/usr/lib/python3.6/site-packages/neovim/api/nvim.py", line 242, in command
    return self.request('nvim_command', string, **kwargs)
  File "/usr/lib/python3.6/site-packages/neovim/api/nvim.py", line 140, in request
    res = self._session.request(name, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/neovim/msgpack_rpc/session.py", line 98, in reques
t
    raise self.error_wrapper(err)
neovim.api.nvim.NvimError: b'Vim:E20: Mark not set'
Password unchanged.
```

Even though the temporary file has been successfully opened in another buffer, pass sees the error from the editor and bails, so changes are not made.

Version info:
nvr 2.0.4
NVIM v0.2.3-774-g611351677
pass  v1.7.1

**Comment by munyari** [comment]
I've stripped this down substantially. In a script called test I have the content
```
$EDITOR
```

Running `EDITOR="nvr +'set spell'" ./test` is enough to reproduce the error.

**Comment by mhinz** [comment]
In this case, using `$EDITOR` is wrong. It should be `eval "$EDITOR"`.

This is actually a bug in `pass`. The arguments passed to the python process are wrong already, so there's nothing I can do about it from nvr.

This works, prints its option `-c` and executes the argument given to that option:

```
FOO='python3 -c "import sys; print(sys.argv)"' bash -c 'eval "$FOO"'
```

This does not work and fails at the first space in the argument given to the option:

```
FOO='python3 -c "import sys; print(sys.argv)"' bash -c '$FOO'
```

[This line in pass](https://github.com/zx2c4/password-store/blob/a6ef408f1db6c2a1abfd2bb337f43583f6cac89b/src/password-store.sh#L481) should be:

```sh
eval "${EDITOR:-vi}" "$tmp_file"
```

Git handles it the same way: https://github.com/git/git/blob/468165c1d8a442994a825f3684528361727cd8c0/git-sh-setup.sh#L156

Unfortunately the project doesn't accept PRs on GitHub and requires people to send patches to its mailing list. I'll leave that task to you. :-)

**Comment by munyari** [comment]
Awesome, thank you for the guidance :smile

**Comment by mhinz** [comment]
You're welcome! :)

**Comment by mhinz** [comment]
Oh, one thing I forgot to mention.. when nvr is called from another program, you almost always have to use any of the wait options. So, when pass got fixed, you'll have to use this:

```
EDITOR="nvr --remote-wait +'set spell'" pass edit tmp
```
