### ISSUE TITLE
nvr --remote-tab* creates an empty tab when it spawns a new neovim server

### ISSUE THREAD

**Issue by MiSawa** [mhinz/neovim-remote#84]
When we call, for instance, `nvr --remote-tab-silent a` and we don't have the neovim server instance yet the spawned neovim instance has two tabs, `[No Name]`, `a`.
This doesn't match the behavior of `vim --remote-tab-silent a` which only creates `a`.
I think it makes sense to call `:edit` for the first file even in `--remote-tab*` (or maybe add an option to do that) when we spawn a new server.

**Comment by mhinz** [comment]
You're right, that's inconvenient and `nvr -p file` already acts properly.

I'll make them behave the same tonight.

**Comment by mhinz** [comment]
Fixed. Thanks for reporting! ✨

**Comment by MiSawa** [comment]
Thank you for your quick action!!:smile:
Although it works fine for a single file (and this is what I almost always use), and `-p` works fine even for multiple files, it looks like `nvr --remote-tab-silent a b` opens both `a` an `b` with `:edit` which results in the same tab :cry:

**Comment by mhinz** [comment]
*\*doh\**

Obviously we also have to check if the first buffer was handled already, otherwise it would use `:edit` all the time. My bad!

Uploaded a new version.
