### ISSUE TITLE
Make friends

### ISSUE THREAD

**Issue by aemonge** [mhinz/neovim-remote#85]
By combining this plugin from neo-vim / vim8 and your amezing work, you have an super powerfull terminal!!!

Please link it somewhere in the description, I get nothing else but the satisfaction of making the world a better CLI  with the link, shougo may get more attention though :)

https://github.com/Shougo/deol.nvim

Cheers

**Comment by mhinz** [comment]
I never used that plugin, but when I'll do and I like it and it fits with nvr, I'll add it to the README.

Thanks!
