### ISSUE TITLE
Problems with relative file paths since neovim 0.3.0 and nvr 2.0.7

### ISSUE THREAD

**Issue by jan0sch** [mhinz/neovim-remote#87]
Since the last updates I have experienced a problem with opening files with relative paths.

neovim : 0.3.0
neovim-remote: 2.0.7

1. Setup neovim and nvr as described in the documentation.
2. Start nvim from a directory (we use `${HOME}` in this example)
3. Open a file from the directory from within the directory via `nvr file.txt` works like expected.
4. Opening a file from another directory will not work unless the absolute path is specified.

Has anyone else experienced this or am I just missing something?

**Comment by pierreganty** [comment]
I also have a simialr problem when invoking `nvr file.txt` from a terminal open within neovim.
It does not open the file from the current directory of the shell but from the directory pointed by `:pwd` it seems.
neovim-remote: 2.0.7
neovim: NVIM v0.3.1-3-g315b7f863

**Comment by mhinz** [comment]
Argh. This is a new regression that I introduced while fixing https://github.com/mhinz/neovim-remote/issues/86.

I'll look into it.

**Comment by mhinz** [comment]
This is actually pretty tricky to get right, because I can't just convert the given path to an absolute one because of #86.

The only good alternative that I see at the moment, is switching the directory within Vim (`:cd`) before opening the file and switching back afterwards. The user won't notice it, until he tries to use `:cd -` and doesn't land in the directory he assumed. Unfortunately I don't see any other way to do this without clobbering the _last used directory_.

**Comment by mhinz** [comment]
I thought about that too, and perhaps this is the least surprising solution. `isUrlOrWhatever?()` would have to match against all the patterns defined by the standard netrw plugin (`:au Network`).

**Comment by jan0sch** [comment]
Maybe a regex checking for a scheme like `^[a-z]+:\/\/` should be enough?

**Comment by pierreganty** [comment]
The website regexlib provides such regexp. 
A quick search for the top rated regexp for `url` returns [this list](http://www.regexlib.com/Search.aspx?k=url&c=-1&m=5&ps=20).

**Comment by mhinz** [comment]
I now used the exact patterns used by netrw.

Please check the latest version from PyPI!

**Comment by pierreganty** [comment]
Solved my problem

**Comment by jan0sch** [comment]
Works also for me. Thank you very much.
