### ISSUE TITLE
Allow sending exit code with `BufDelete` event

### ISSUE THREAD

**Issue by hauleth** [mhinz/neovim-remote#89]
This would allow users to define command to exit buffer with error code, which would be useful in case of setting `nvr` as e Git editor.

**Comment by mhinz** [comment]
I guess you're using `git commit` from within `:terminal` and want to create a command that works like `:cquit` without actually quitting Nvim?

**Comment by hauleth** [comment]
Exactly.

**Comment by mhinz** [comment]
Should work now with v2.1.0.

Thanks!

**Comment by beelzebielsk** [comment]
I'd like to make use of this myself. How would I?

**Comment by beelzebielsk** [comment]
After some more research, the channel number is already exposed via `b:nvr`.
