### ISSUE TITLE
Can't connect to /tmp/nvim

### ISSUE THREAD

**Issue by Alok** [mhinz/neovim-remote#9]
I exported NVIM_LISTEN_ADDRESS as /tmp/nvim in my `zshrc` and tried to run `nvr --serverlist` both in the nvim term and a regular terminal, only to get no output from either. Attempting to open a file just gave the error:

```
Can't connect to /tmp/nvim. Export $NVIM_LISTEN_ADDRESS or use --servername                            
```

**Comment by mhinz** [comment]
First of all, `nvr --serverlist` should always give you output, execept when `NVIM_LISTEN_ADDRESS` is set to an empty string. What's the output of `echo $NVIM_LISTEN_ADDRESS` immediately before `nvr --serverlist`?

And `nvr` will never start Neovim for you. If there's no server nvim instance running that is connected to `/tmp/nvim` (check `:echo v:servername`), then you'll get that error message.

**Comment by Alok** [comment]
I ran `:echo v:servername` and got `/tmp/nvimsocket`. Setting my environment var to that in my zshrc fixed the issue. Thanks for the heads-up about the error message.
