### ISSUE TITLE
Is neovim-remote compatible with `--listen` option?

### ISSUE THREAD

**Issue by qubidt** [mhinz/neovim-remote#91]
`NVIM_LISTEN_ADDRESS` [has been deprecated in favor of the `--listen` argument](https://github.com/neovim/neovim/pull/8247) as of `0.3.0` (I know @mhinz is aware because he commented in the PR). Does neovim-remote have any way of syncing the socket nvim uses?

@justinmk mentioned:

> I will introduce a new env var `$NVIM` which will be set only in `:terminal` and will not be passed down to grandchildren.

This, as far as I can see, doesn't seem to be implemented yet? Or am I just missing something?

**Comment by mhinz** [comment]
What do you mean with syncing the socket?

If you just want to set the address via `--listen`, I'll introduce that option as an alias for the already existing `--servername` (naming from Vim).

> > I will introduce a new env var `$NVIM` which will be set only in `:terminal` and will not be passed down to grandchildren.
> 
> This, as far as I can see, doesn't seem to be implemented yet? Or am I just missing something?

Nope, I'm not seeing it either. :)

**Comment by qubidt** [comment]
> What do you mean with syncing the socket?

I meant that when calling `nvr` from a neovim `:terminal`,  neovim-remote depends on `NVIM_LISTEN_ADDRESS` for the socket name. I assumed that since this was being deprecated that I would have to handle passing nvim's `v:servername` to `nvr` manually. It appears that [nvim still handles setting `NVIM_LISTEN_ADDRESS`], so nvr-remote functions correctly anyways (I should have tested before filing an issue!)

> If you just want to set the address via --listen, I'll introduce that option as an alias for the already existing --servername (naming from Vim).

Thank you, but there's no need for that. :smile:

**Comment by qubidt** [comment]
On second thought, nvr is not aware of the server address generated by [`server_address_new`](https://github.com/neovim/neovim/blob/cafb92487b308b44f38d004c6d1c540f00656021/src/nvim/msgpack_rpc/server.c#L46) when nvr is launched from a separate terminal rather than a nvim `:terminal`, so it would still be nice to have nvr handle this if `NVIM_LISTEN_ADDRESS` is truly deprecated. 

I'm not that well versed about neovim. Do you have any thoughts on how this would be implemented? Or is it best to just set a static socket name that is passed to nvim at startup and `nvr --remote`?

**Comment by mhinz** [comment]
Do you have a certain use case that is _not_ working? I'm still not sure what's the actual issue. :-)

Nvim uses a default Unix socket by default when it starts. That's what you see with `:echo v:servername` (and still `$NVIM_LISTEN_ADDRESS`).

You can start additional servers, e.g. `:call serverstart('/tmp/foo')`. That won't change `v:servername` though if it was already set.

You can see both servers with `:echo serverlist()`.

And `nvr --serverlist` should also list both server addresses. Then you can use `nvr --servername <address> --remote ...`.

**Comment by qubidt** [comment]
> `:call serverstart('/tmp/foo')`

and 

> `nvr --serverlist`

were what I was missing, thank you! I didn't know about these.
