### ISSUE TITLE
Occasional error starting up

### ISSUE THREAD

**Issue by davidosomething** [mhinz/neovim-remote#99]
```Traceback (most recent call last):
  File "/Users/dotrakoun/.config/pyenv/versions/3.7.0/bin/nvr", line 11, in <module>
    sys.exit(main())
  File "/Users/dotrakoun/.config/pyenv/versions/3.7.0/lib/python3.7/site-packages/nvr/nvr.py", line 561, in main
    nvr.server.close()
AttributeError: 'NoneType' object has no attribute 'close'```

**Comment by mhinz** [comment]
"Occasional"? :)

- Does it only happen if nvr itself starts a new nvim process or also when it uses an already existing process?
- Does it happen with just `nvr` (without arguments) as well?

**Comment by davidosomething** [comment]
i always start with `PYTHONWARNINGS=ignore nvr -s` (and optionally a filename)
it might be when there's a hanging process (e.g. crashed terminal leaving invalid socket file)

**Comment by mhinz** [comment]
Maybe `PYTHONWARNINGS=default` would get us a hint. :)

In the meanwhile I'll check if I can break nvr by giving it stale sockets etc.

**Comment by mhinz** [comment]
I did another few fixes today. Accessing `nvr.server` when it's None should not happen anymore.

I also fixed a few warnings that should only happen with `PYTHONWARNINGS=default`, but some can't be fixed from my side. They need changes in pynvim. But these are `unclosed transport` warnings and can be ignored.

Please reopen this as soon as you get an issue again.
